=== lunatech-labs/lunatech-competence-center-online/core-curriculum/schema/knowledge-graph.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {},
  "id": "lunatech-core-curriculum-knowledge-graph-schema",
  "properties": {
    "description": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "image": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "tags": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "topics": {
      "items": {
        "properties": {
          "abilities": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "assessment-questions": {
            "items": {
              "properties": {
                "answer-hint": {
                  "type": "string"
                },
                "question": {
                  "type": "string"
                }
              },
              "required": [
                "question"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "dependencies": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "description": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "resources": {
            "items": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "notes": {
                  "type": "string"
                },
                "type": {
                  "type": "string",
                  "enum": ["video", "article", "book", "documentation", "other"]
                },
                "url": {
                  "type": "string"
                }
              },
              "required": [
                "url",
                "type",
                "name"
              ],
              "type": "object"
            },
            "type": "array"
          },
          "tags": {
            "items": {
              "type": "string"
            },
            "type": "array"
          }
        },
        "required": [
          "description",
          "id",
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    }
  },
  "required": [
    "description",
    "id",
    "topics",
    "name"
  ],
  "type": "object"
}

=== lunatech-labs/lunatech-competence-center-online/core-curriculum/knowledge/networking.json
{
    "id":"networking",
    "name":"Networking",
    "description":"Networking is about computer wiring computers together and having them talk to each other.",
    "tags":["uhm","TODO"],
    "image": "",
    "topics": [
        {
            "id":"basic",
            "name":"Basic Networking",
            "description": "Basic knowledge of the components of a minimal (home) computer network.",
            "tags": [],
            "resources":[
                {
                    "name":"Linuxjourney - network-basics",
                    "type":"documentation",
                    "url":"https://linuxjourney.com/lesson/network-basics"
                }
            ],
            "abilities": [
                "List components of a home computer network and their function, e.g: devices, cables, access points, router, modem."
            ]
        },
        {
            "id":"addressing-transport",
            "name":"Adressing and transport",
            "description":"Computers talk to each other using various addresses, MAC, IPv4. We start with MAC / IPv4. dwdwIPv6 will be discussed later, as further knowledge makes it easier to understand the advantages and tradeoffs related to IPv6. This topic also starts on the OSI model.",
            "dependencies":["basic"],
            "resources":[
                {
                    "name":"Linuxjourney - Network Adressing",
                    "type":"documentation",
                    "url":"https://linuxjourney.com/lesson/network-addressing"
                },
                {
                    "name":"Wikipedia - OSI model (media layer)",
                    "type":"documentation",
                    "url":"https://en.wikipedia.org/wiki/OSI_model",
                    "notes": "Focus on the media layer"
                },
                {
                    "name":"Linuxjourney - Subnetting",
                    "type":"documentation",
                    "url":"https://linuxjourney.com/lesson/ipv4",
                    "notes":"1. IPv4 up to 5. CIDR"
                }
            ],
            "abilities": [
                "Describe the purpose and properties of a MAC address, and on what OSI layer it applies.",
                "Describe the purpose and properties of an IPV4 address, and on what OSI layer it applies.",
                "Understand CIDR notation.",
                "Understand: ARP, broadcasting, and and how connections are setup within the subnet a computer belongs to."
            ]
        },
        {
            "id":"tcpip",
            "name":"Layer 4: TCP & UDP",
            "description":"The TCP/IP model, what currently \"runs\" the internet and most other networks.",
            "dependencies":["addressing-transport"],
            "resources":[
                {
                    "name":"Linuxjourney - TCP/IP Model",
                    "type":"documentation",
                    "url":"https://linuxjourney.com/lesson/tcp-ip-model"
                },
                {
                    "name":"Wikipedia - OSI model (protocol layer)",
                    "type":"documentation",
                    "url":"https://en.wikipedia.org/wiki/OSI_model",
                    "notes": "Focus on the media layer"
                }
            ],
            "abilities": [
                "Describe what ports are.",
                "Describe the properties of TCP connections.",
                "Describe the properties of UDP transmissions."
            ]
        },
        {
            "id":"dhcp",
            "name":"DHPC",
            "description":"DHCP is the technology used to assign IP adresses to network clients. Commonly a DHCP server distributes IP adresses within one or more subnets.",
            "dependencies":["addressing-transport"],
            "resources":[
                {
                    "name":"Linuxjourney - DHCP overview",
                    "type":"documentation",
                    "url":"https://linuxjourney.com/lesson/dhcp-overview"
                }
            ],
            "abilities":[
               "Explain the purpose of a DHCP server."
            ]
        },
        {
            "id":"reserved-nets",
            "name":"Reserved Subnets",
            "description":"A group of subnets is reserved for special purposes that cannot be used on the internet.",
            "dependencies":["addressing-transport"],
            "resources":[
                {
                    "name":"Wikipedia - Table of reserved ranges and their purpose.",
                    "type":"documentation",
                    "url":"https://en.wikipedia.org/wiki/Reserved_IP_addresses"
                }
            ],
            "abilities":[
                "Know what reserved network ranges are.",
                "Know where to find out if a network range is reserved for a specific purpose or not."
            ]
        },
        {
            "id":"routing-local",
            "name":"Local Routing",
            "description":"Routing is used for connecting to devices that are not on the local subnet, often it involved jumps trough several hosts (known as routers). The first router is referred to as the internet gateway for a subnet.",
            "dependencies":["addressing-transport","addressing-transport"],
            "resources":[],
            "abilities":[
                "Explain how a routing table works on the OS level."
            ]
        },
        {
            "id":"bridging",
            "name":"Bridges",
            "description":"Bridging is used to connect different networks using a lower level device than a router.",
            "dependencies":["addressing-transport","addressing-transport"],
            "resources":[],
            "abilities":[
                "Explain the properties of a network bridge (i.e.: layer 2 device)",
                "Give common use cases of a bridge (e.g.: multiple VMs with distinct addresses on a single network port"
            ]
        },
        {
            "id":"nat",
            "name":"NAT",
            "dependencies":["addressing-transport","routing-local"],
            "description":"Network Access Translation (NAT) is something performed on the internet gateway of a private network with a reserved address space (e.g.: 192.168.0.0/16). The NAT rewrites the IP addresses in the packages of the traffic to one or more external IP addresses to allow proper internet connectivity. In addition to that the NAT keeps track of connections and makes sure traffic flows to and from the right hosts.",
            "resources":[],
            "abilities":[
                "Explain the purpose of a NAT.",
                "Understand the basic functioning of a NAT, e.g.: why are port forwarding rules needed for incoming traffic but not for incoming responses to outbound traffic."
            ]
        },
        {
            "id":"dns",
            "name":"DNS",
            "description":"To get from numeric addresses to fancy names like \"learn.lunatech.com\" the Domain Name System (DNS) is used.",
            "dependencies":["addressing-transport"],
            "resources":[],
            "abilities":[
                "Basic knowledge of DNS, e.g.: MX, A, CNAME, SOA and NS records",
                "Explain how recursive DNS queries work.",
                "Explain the difference between a local DNS server (that serves a local domain) and a DNS cache.",
                "Explain the purpose of the TTL and when/why you would want to give this a high or low value."
            ]
        },
        {
            "id":"dns-advanced",
            "name":"DNS - Advanced",
            "description":"Advanced usages of DNS, e.g.: round-robin load balancing using DNS, DNAME zones",
            "dependencies":["dns"],
            "resources":[],
            "abilities":[
                "Explain how DNS can be used for (global) load balancing.",
                "Understand more advanced records such as the various TXT values, SRV and DNAME records.",
                "Explain the purpose of DNSSEC."
            ]
        },
        {
            "id":"routing-global",
            "name":"Global Routing", 
            "description":"Routing beyond the local routing table and the various protocols used by routers to make the internet work will be discussed here..",
            "dependencies":["routing-local"],
            "resources":[],
            "abilities":[
                "Explain how routing works on a global level.",
                "Explain the purpose of BGP.",
                "Explain what an \"Autonomous System Number\" is"
            ]
        },
        {
            "id":"virtual",
            "name":"Virtual networks",
            "description":"There are various technologies in use to run virtual networks. Examples of this include VLANs which allow multiple layer 2 domains to co-exist on one physical network, VPNs, and more advanced overlay networks such as Calico.",
            "dependencies":["addressing-transport","routing-local"],
            "resources":[]
        }
    ]
}

=== lunatech-labs/lunatech-competence-center-online/core-curriculum/knowledge/sbt.json
{
	"id": "sbt",
  "name": "SBT, interactive build tool",
  "description": "The industry-standard build tool for Scala",
  "tags": ["tool"],
  "topics": [
    {
      "id": "basic-usage",
      "name": "Basic usage of SBT",
      "description": "Creating new SBT projects, and using the most common tasks for compiling, running and testing your code.",
      "resources": [
        {
          "name": "SBT Documentation",
          "type": "documentation",
          "url": "http://www.scala-sbt.org/documentation.html",
          "tags": ["official"]
        }
      ],
      "abilities": [
        "Create a new SBT project with a 'hello-world' scala program",
        "Automatically recompile, run or execute tests when the code changes",
        "Run only a single test",
        "Use dependencies from Maven Central"
      ],

      "assessment-questions": [
        { "question": "How do you execute a task on every code change?" },
        { "question": "What's the normal directory structure; where do you put scala source code and tests?" },
        { "question": "How do you set the scala version of the project?" },
        { "question": "What's the difference in syntax between depending on a Scala and a Java library? Why is it different?", "answer-hint": "One '%' for Java, and two for Scala dependencies between group id and artifact id. The reason is that during publishing, the Scala binary version is added to the artifact id."},
        { "question": "Can you use a library compiled for Scala 2.11 with Scala 2.12?" },
        { "question": "What's the difference between `update` and `reload`? When do you use them?", "answer-hint": "`update` fetches the dependencies, `reload` reloads the sbt configuration. You need to use `reload` after you changed the sbt configuration. `update` is almost never needed, when you run or compile it's automatically executed."}
      ]
    },
    {
      "id": "plugins",
      "name": "Using Plugins",
      "description": "SBT has many plugins. Some important plugins to know are `scalafmt`, `sbt-updates` and `sbt-dependency-graph`, `sbt-buildinfo`.",
      "dependencies": ["basic-usage"],
      "resources": [],
      "abilities": [
        "Install a plugin in the project, or globally",
        "Have your code automatically formatted on every compile",
        "Check if all your dependencies are at the latest version",
        "Figure out how your application depends on a particular dependency that ends up on the classpath",
        "Use the BuildInfo plugin to add the application version to your compiled application"
      ],

      "assessment-questions": [
        { "question": "How do you install a plugin for a single project?" },
        { "question": "How do you install a plugin globally?" },
        { "question": "Which kind of plugins would you install globally? Which ones locally?", "answer-hint": "Plugins that the project requires (like sbt-scalaxb for example) should be installed in the project. Plugins that are for you as a developer (like sbt-updates, sbt-ensime) are preferably installed globally." }
      ]
    },
    {
      "id": "publishing",
      "name": "Publishing libraries",
      "description": "Libraries can be published",
      "resources": [],
      "dependencies": ["using-plugins"],
      "abilities": [
        "Publish a library to Artifactory",
        "Configure a project to be cross-published for multiple Scala-versions",
        "Use the `sbt-release` plugin to structure deployment"
      ],
      "assessment-questions": [
        { "question": "What is the proper order of bumping the version, publishing, tagging in Git and pushing to Git?", "answer-hint": "* Bump the version to the release version\n* Publish and tag in Git\n*Bump to the next development version\n*Push to Git" },
        { "question": "What do you need to do if your code needs to be slightly different between multiple Scala versions?" },
        { "question": "How do you publish a library for use from ScalaJS?" }
      ]
    },
    {
      "id": "creating-tasks",
      "name": "Creating custom tasks",
      "description": "Make your own tasks to automate stuff",
      "resources": [],
      "dependencies": ["basic-usage"],
      "abilities": [
        "Create a task that runs a shell command",
        "Create a task that generates some source code which gets used by the main application sources, and which gets automatically triggered by `compile`"
      ],
      "assessment-questions": [
        { "question": "What's the difference between a TaskKey and a SettingKey?", "answer-hint": "SettingKey is only evaluated once, TaskKey everytime the task runs" },
        { "question": "How do you make a task that depends on the result of another task?", "answer-hint": "Using the other task name, and then `.value` (which is a macro that only works inside task definitions)"}
      ]
    },
    {
      "id": "creating-plugins",
      "name": "Creating plugins",
      "description": "How to create plugins",
      "resources": [],
      "dependencies": ["creating-tasks", "using-plugins", "publishing"],
      "abilities": [
        "Create an SBT plugin",
        "Publish an SBT plugin on Artifactory",
        "Make a plugin automatically insert new tasks into the project that it's added to"
      ]
    }
  ]
}
